name: VSphere Packer Build

on:

  push:
    branches: [ main ]
    paths:
      - 'Packer/**'

jobs:
  packer:
    runs-on: self-hosted
    strategy:
      matrix:
        template: ["RHEL-K8s-Controller", "RHEL-K8s-Worker", "Github-Runner"]
    env:
      PKR_VAR_REDHAT_ORGID: ${{ secrets.REDHAT_ORGID }}
      PKR_VAR_RHEL_ACTIVATION_KEY: ${{ secrets.RHEL_ACTIVATION_KEY }}
      PKR_VAR_ssh_password: ${{ secrets.SETUP_PASSWORD }}
      PKR_VAR_ssh_username: ${{ secrets.SETUP_USERNAME }}
      PKR_VAR_password: ${{ secrets.VCENTER_PASSWORD }}
      PKR_VAR_vcenter_server: ${{ secrets.VCENTER_SERVER }}
      PKR_VAR_username: ${{ secrets.VCENTER_USERNAME }}
    defaults:
      run:
        working-directory: ./Packer/${{ matrix.template }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6


      - name: Get Runner IP Address
        id: get_ip
        run: |
         whoami
         echo "HOME=$HOME"
         ls -R ~/.config/packer || echo "no plugins"
         packer version
         echo "ip=$(hostname -I | cut -d " " -f 1)" >> $GITHUB_OUTPUT
         pwd
         ls -la
      - name: Packer Init
        run: packer init .

      - name: Packer Format Check
        run: packer fmt -check .

      - name: Packer Validate
        env: 
          PKR_VAR_bind_address: ${{ steps.get_ip.outputs.ip }}
        run: packer validate .

      - name: Packer Build
        env: 
          PKR_VAR_bind_address: ${{ steps.get_ip.outputs.ip }}
        run: packer build -force .
