name: Build and Test RHEL Worker

on:
  workflow_call:

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./Packer/RHEL-K8s-Worker/
    steps:
      - name: Checkout
        uses: actions/checkout@v6


      - name: Get Runner IP Address
        id: get_ip
        run: |
         echo "ip=$(hostname -I | cut -d " " -f 1)" >> $GITHUB_OUTPUT

      - name: Packer Init
        run: /usr/bin/packer init .

      - name: Packer Format Check
        run: /usr/bin/packer fmt -check .

      - name: Packer Validate
        env: 
          PKR_VAR_bind_address: ${{ steps.get_ip.outputs.ip }}
        run: /usr/bin/packer validate .

      - name: Packer Build
        env: 
          PKR_VAR_bind_address: ${{ steps.get_ip.outputs.ip }}
        run: /usr/bin/packer build -force .

  test:
    needs: build
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./Tofu/live/RHEL-K8s-Worker/
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Tofu Init
        run: tofu init

      - name: Set Workspace
        run: |
          tofu workspace select dev || tofu workspace new dev

      - name: Tofu Plan
        run: tofu plan

      - name: Tofu Build
        run: tofu apply -auto-approve

  kubernetes-build:
    needs: test
    uses: ./.github/workflows/kubernetes-tests.yml
    secrets:
      AWS_DEFAULT_REGION: wnam
      AWS_ENDPOINT_URL_S3: ${{ secrets.CLOUDFLARE_BUCKET_URL }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_BUCKET_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_BUCKET_ACCESS_KEY_ID }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_R2_API }}

  destroy:
    needs: kubernetes-build
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./Tofu/live/RHEL-K8s-Worker/
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Tofu Init
        run: tofu init

      - name: Set Workspace
        run: |
          tofu workspace select dev || tofu workspace new dev

      - name: Tofu Destroy
        run: tofu destroy -auto-approve


  request:
    needs: destroy
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./Tofu/live/RHEL-K8s-Worker/
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Tofu Init
        run: tofu init

      - name: Set Workspace
        run: |
          tofu workspace select prod || tofu workspace new prod

      - name: Tofu Plan
        run: tofu plan
